### ISSUE TITLE
Two small visual bugs

### ISSUE THREAD

**Issue by Abyss777** [vitalidze/traccar-web#156]
There are ~~two~~ three very small visual bugs:
- There is an unnecessary white column in Account config popup window
  ![account-bug](https://cloud.githubusercontent.com/assets/5688080/7346304/7851b05c-ecf6-11e4-9f7a-4cdfbf096098.png)

After resizing it is almost disappearing, but after reopening it is here again. 
- Reserved line height is not enough in Global config popup window. The language name is cut a bit.

![global-bug](https://cloud.githubusercontent.com/assets/5688080/7346342/dcceefb8-ecf6-11e4-9722-f118e62b21c4.png)

After resizing it is normal, but after reopening it is here again.
It is appears in Russian locale, but in English is OK.
- Sometimes menu appears under zoom buttons

![zoom keys-bug](https://cloud.githubusercontent.com/assets/5688080/7346555/055e24ec-ecf9-11e4-8451-a61665bd377e.png)

It happens not always, but very frequently (especially after page loading)

**Comment by vitalidze** [comment]
First one should perform better now, second one is fixed, written [news](http://traccar.litvak.su/2015/04/28/bugfix-release.html), updated [latest](myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo](http://traccar.litvak.su/demo.html) versions.

Have no idea what to do with the third one...

**Comment by Abyss777** [comment]
OK. It's not much annoying. 
I've noticed that it happens only after page had been loaded and before device markers appeared on the map. (5-10 seconds).
If you still have no idea whats wrong, I suggest to close this issue.

**Comment by vitalidze** [comment]
If first two are fine for you now, please close it.

**Comment by Abyss777** [comment]
Unfortunately, the first one is not solved. I've tested in FF and Chrome.I've cleared cookies and used incognito tab.

**Comment by vitalidze** [comment]
I think I figured that out - white space is for scrollbar. I wasn't able to reproduce it since my main machine runs Mac OS X, where scroll bar is drawn differently - it does not require additional space. But on windows this problem exists. I have fixed it by forcing scroll bar size to 1 pixel. Please try latest version.

**Comment by Abyss777** [comment]
Everything is good now.
Thank you.
